# Generated by Django 2.0.5 on 2018-05-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='Images/')),
                ('name', models.CharField(max_length=30)),
                ('descripton', models.TextField()),
            ],
        ),
    ]
