# Generated by Django 2.0.5 on 2018-05-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_location_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='location_taken',
            field=models.ForeignKey(default=1, on_delete=True, to='display.Location'),
            preserve_default=False,
        ),
    ]
