# Generated by Django 2.0.5 on 2018-05-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0004_auto_20180506_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='photo',
            field=models.ImageField(default=2, upload_to='Images/'),
            preserve_default=False,
        ),
    ]
